### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true  # choices: [true, false]
freeze_multi_modal_projector: true  # choices: [true, false]
freeze_language_model: false  # choices: [true, false]
deepspeed: deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: AesCoT_gpt_3k
# aes_sft_qvq_infer_correct,r1-one-vision-train-4k,
template: qwen2_vl
cutoff_len: 8192
#max_samples: 1000
overwrite_cache: false
preprocessing_num_workers: 32
dataloader_num_workers: 0
### output
output_dir: AesR1/qwen2-5-7b_instruct_AesCoT_gpt_3k_epoch10
logging_steps: 2
save_steps: 47
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.0
bf16: true
enable_liger_kernel: True
ddp_timeout: 180000000
resume_from_checkpoint: null
max_completion_length: 4096
temperature: 1.2
report_to: wandb
run_name: qwen2-5-7b_instruct_AesCoT_gpt_3k
### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500

